# Generated by Django 2.1.2 on 2018-11-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20181107_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test1',
        ),
    ]
